### ISSUE TITLE
Regression: Sync failure after delete record (when using quickstart) (v 0.7.5)

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/web5-js#102]
Following the quickstart with 0.7.5 web5: https://developer.tbd.website/docs/web5/quickstart

code: 
https://gist.github.com/michaelneale/282ea256fc936cca2cc9bfd0087d6903

....
Results in an error: 
```
secp256k1 unavailable, reverting to browser version
Sync failed due to error:  Error: (404) Failed to read data associated with record bafyreig3knfootf2o7f5tladyfkvcc3w2wojp2hwa7uwn6hrj7fexfahzy. Not Found}
    at _SyncApi.<anonymous> (file:///Users/micn/Documents/code/web5-app/node_modules/@tbd54566975/web5-user-agent/dist/esm/main.mjs:977:17)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/micn/Documents/code/web5-app/node_modules/@tbd54566975/web5-user-agent/dist/esm/main.mjs:46:24)
```

Update: it does delete it - but then sync kills it: 
```
delete result { status: { code: 202, detail: 'Accepted' } }
Sync failed due to error:  Error: (404) Failed to read data associated with record bafyreib56qrdl2o4b3mhrlqha7pj767xgttzhrspcn4faetb63pwtfybqu. Not Found}
    at _SyncApi.<anonymous> (file:///Users/micn/Documents/code/web5-app/node_modules/@tbd54566975/web5-user-agent/dist/esm/main.mjs:977:17)
    at Generator.next (<anonymous>)
    at fulfilled (file:///Users/micn/Documents/code/web5-app/node_modules/@tbd54566975/web5-user-agent/dist/esm/main.mjs:46:24
```

**Comment by michaelneale** [comment]
@mistermoe you can see it after it tries to sync

**Comment by michaelneale** [comment]
@mistermoe seems to be trying to delete that causes it. This was not the case before this version (which I think has sync on it). Will need to start with fresh data store of course.

**Comment by mistermoe** [comment]
@michaelneale thanks for the reproducible gist
