### ISSUE TITLE
React Native: Correct package.json configuration for module resolution? Error: Unable to resolve module @web5/dids/utils from tech-preview.js?

### ISSUE THREAD

**Issue by andorsk** [TBD54566975/web5-js#213]
**Expected** React Native import of Web5 libs work
**Actual** I'm having some issues with module resolution in React Native. With a fresh React Native app and just importing web5/api to the project, I get the following problem: 
**Web5 Version**: 0.8.1
**React Native Version**: 0.71.7

```sh
 BUNDLE  ./index.js 

error: Error: Unable to resolve module @web5/dids/utils from  /node_modules/@web5/api/dist/esm/tech-preview.js: 

None of these files exist:
  * node_modules/@web5/dids/utils(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
  * node_modules/@web5/dids/utils/index(.native|.ios.js|.native.js|.js|.ios.jsx|.native.jsx|.jsx|.ios.json|.native.json|.json|.ios.ts|.native.ts|.ts|.ios.tsx|.native.tsx|.tsx)
   8 |     });
   9 | };
> 10 | import * as didUtils from '@web5/dids/utils';
     |                            ^
  11 | /**
  12 |  * Dynamically selects up to 2 DWN endpoints that are provided
  13 |  * by default during the Tech Preview period.
    at ModuleResolver.resolveDependency (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 9)
    at async Graph._processModule (/Users/akmb2/workspace/github.com/zion/prototype/adsf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/akmb2/workspace/github.com/zion/prototype/asdf/node_modules/@react-native-community/cli-plugin-metro/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 6)
```

any suggestions on how to resolve them?

**Comment by amika-sq** [comment]
Discussed this on Discord here: https://discord.com/channels/937858703112155166/1149735848783392788

`@web5/dids/utils` is a named export, which React Native currently doesn't support (it's [in beta](https://reactnative.dev/blog/2023/06/21/0.72-metro-package-exports-symlinks#package-exports-support-beta), but I've not been able to get it working properly myself yet).

There's been discussion about removing the named exports, but as of this moment they're still in some `@web5`, which is causing the issue.

In the meantime, we've been using the patch-package npm package to locally patch `@web5` packages in the `web5-wallet` repo. Here's a link to the packages we currently do in the wallet repo:
https://github.com/TBD54566975/web5-wallet/tree/main/patches

**Comment by andorsk** [comment]
Thanks @frankhinek
