### ISSUE TITLE
`did:dht` resolution fails

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/web5-js#312]
Hitting the following error when attempting to resolve `did:dht` DIDs:

code:
```typescript
const did = await DidDhtMethod.create();
const didResolutionResult = await DidDhtMethod.resolve({ didUrl: did.did });
```

error:
```
Error: Invalid SignedPacket bytes length, expected at least 72 bytes but got: 25
  at SignedPacket.fromBytes (file:///Users/moe/code/tbd/ose/web5/node_modules/pkarr/lib/signed_packet.js:75:13)
  at Pkarr.relayGet (file:///Users/moe/code/tbd/ose/web5/node_modules/pkarr/index.js:46:25)
```

**Comment by decentralgabe** [comment]
This is a result of attempting to fetch the DID before it has published, which takes about 10 seconds. The error can be better but I wouldn't classify it as a bug.

**Comment by mistermoe** [comment]
kk thanks! this works:

```js
const sleep = (time) => new Promise(resolve => setTimeout(resolve, time));

const did = await DidDhtMethod.create({ publish: true });

await sleep(10_000);
const didResolutionResult = await DidDhtMethod.resolve({ didUrl: did.did });
```

agree that it's not a bug and agree that the error message could be better. removed the bug label and updated the github issue description to reflect
