### ISSUE TITLE
Web5.js not inegrated with React native cli 

### ISSUE THREAD

**Issue by Zer-0ne** [TBD54566975/web5-js#315]
there is problem in intergation web5 api with react native

code:
![image](https://github.com/TBD54566975/web5-js/assets/118300201/9b28a2fe-2a06-4966-8fdd-f04f5e785826)

error:
error: Error: While trying to resolve module `multiformats` from file `/home/eagle/Documents/web5_music_app/music_app/node_modules/@web5/common/dist/esm/multicodec.js`, the package `/home/eagle/Documents/web5_music_app/music_app/node_modules/@web5/common/node_modules/multiformats/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/home/eagle/Documents/web5_music_app/music_app/node_modules/@web5/common/node_modules/multiformats/index`. Indeed, none of these files exist:

  * /home/eagle/Documents/web5_music_app/music_app/node_modules/@web5/common/node_modules/multiformats/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /home/eagle/Documents/web5_music_app/music_app/node_modules/@web5/common/node_modules/multiformats/index/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/node-haste/DependencyGraph.js:289:17)
    at Object.resolve (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/lib/transformHelpers.js:169:21)
    at Graph._resolveDependencies (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/DeltaBundler/Graph.js:473:35)
    at Graph._processModule (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/DeltaBundler/Graph.js:261:38)
    at async Graph._addDependency (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 1)
    at async Graph._processModule (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/DeltaBundler/Graph.js:322:5)
    at async Graph._addDependency (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/DeltaBundler/Graph.js:372:20)
    at async Promise.all (index 5)
    at async Graph._processModule (/home/eagle/Documents/web5_music_app/music_app/node_modules/metro/src/DeltaBundler/Graph.js:322:5)

![image](https://github.com/TBD54566975/web5-js/assets/118300201/b66fbd3e-404d-47f5-b48f-245278f7625a)

**Comment by phillipnunes** [comment]
up, I have the same issue here
