### ISSUE TITLE
Web5 depends on latest stable version of Node (v18.x)

### ISSUE THREAD

**Issue by ALRubinger** [TBD54566975/web5-js#71]
When running the Quickstart `index.js`: 

```
import { Web5 } from '@tbd54566975/web5';

const { web5, did: aliceDid } = await Web5.connect();

const { record } = await web5.dwn.records.create({
    data: "Hello Web5",
    message: {
      dataFormat: 'text/plain',
    },
});

const { records } = await web5.dwn.records.query({
  message: {
    filter: {
      dataFormat: 'text/plain'
    }
  }
});

const readResult = await record.data.text();
console.log(readResult);
const updateResult = await record.update({ data: "Hello, I'm updated!" });
console.log(updateResult);
const deleteResult = await record.delete();
console.log(deleteResult)

```

...fails on `16.x`:

```
nvm use v16.18.0
Now using node v16.18.0 (npm v8.19.2)
 quickstart  node src/index.js
secp256k1 unavailable, reverting to browser version
file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:90
    dataBlob = new Blob([data], { type: "text/plain" });
    ^

ReferenceError: Blob is not defined
    at dataToBlob (file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:90:5)
    at DwnApi.<anonymous> (file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:655:42)
    at Generator.next (<anonymous>)
    at file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:68:61
    at new Promise (<anonymous>)
    at __async (file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:52:10)
    at Object.write (file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:653:27)
    at DwnApi.<anonymous> (file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:533:29)
    at Generator.next (<anonymous>)
    at file:///private/tmp/quickstart/node_modules/@tbd54566975/web5/dist/esm/main.mjs:68:61
```

**Comment by ALRubinger** [comment]
This may require no changes, per @frankhinek - raising only for OSE awareness. Node 18 is an installation prereq for Web5, and that's OK. We are noting it in the docs.

**Comment by frankhinek** [comment]
This was already known by OSE and is why the `package.json` file specifies:

https://github.com/TBD54566975/web5-js/blob/12435a10778ba84ef888d596e789d94dde135548/packages/web5/package.json#L78-L79

Node 18 is the current LTS version and should be noted as a pre-req for documentation.

There are a number of features, like native Node fetch, that weren't added until Node 17.x, and were not removed from the `experimental` list until Node v18.0.0.
