### ISSUE TITLE
messaging test: protocolPath required as well as protocol

### ISSUE THREAD

**Issue by michaelneale** [TBD54566975/web5-js#82]
Trying to setup a simple protocol like: 

```
    var simpleMessageProtocol = {
      "protocol": "http://simple-messaging-protocol.xyz",
      "types": {
        "message": {
          "schema": "http://simple-messaging-protocol.xyz/schemas/message",
          "dataFormats": ["text/plain"]
        },
        "messageResponse": {
          "schema": "http://simple-messaging-protocol.xyz/schemas/message-response",
          "dataFormats": ["text/plain"]
        }
      },
      "structure": {
        "message": {
          "$actions": [
            {
              "who": "anyone",
              "can": "write"
            }
          ],
          "messageResponse": {
            "$actions": [
              {
                "who": "recipient",
                "of": "message",
                "can": "write"
              }
            ]
          }
        }
      }
    };

    var { protocol, status } = await web5.dwn.protocols.configure({
      message: {
        definition: simpleMessageProtocol
      }
    });
```

and trying to use that protocol: 

```
    const { record } = await web5.dwn.records.create({
      to: client2,
      data: "Hello World!",
      message: {
        protocol: "http://simple-messaging-protocol.xyz",
        schema: "mic/sample"
      },
    });
    var { status } = await record.send(client2);
    console.log(status);
```

I get an error: 
`records-write.ts:148 Uncaught Error: `protocol` and `protocolPath` must both be defined or undefined at the same time`

What is a protocolPath?

**Comment by michaelneale** [comment]
I was able to look at code and see it would be message (would be nice to document that somewhere). 

I then simplified my protocol: 

```
    var simpleMessageProtocol = {
      "protocol": "http://simple-messaging-protocol3.xyz",
      "types": {
        "message": {
          "schema": "http://simple-messaging-protocol3.xyz/schemas/message",
          "dataFormats": ["text/plain"]
        },
        "messageResponse": {
          "schema": "http://simple-messaging-protocol3.xyz/schemas/message-response",
          "dataFormats": ["text/plain"]
        }
      },
      "structure": {
        "message": {
          "$actions": [
            {
              "who": "anyone",
              "can": "write"
            },
            {
              "who": "recipient",
              "of": "message",
              "can": "read"
            }
          ],
        }
      }
    };
```

And was able to send from one user: 

    const { record } = await web5.dwn.records.create({
      data: "Hello World!",
      message: {
        protocol: "http://simple-messaging-protocol3.xyz",
        schema: "http://simple-messaging-protocol3.xyz/schemas/message",
        protocolPath: "message"

      },
    });


    
    var { status } = await record.send(client2);
    console.log(status);


which was accepted. 

however, when I tried to query it from another client (client2) (that it was sent to) with the following code: 

```
    // This invocation will query the user's own DWeb Nodes
    const { records } = await web5.dwn.records.query({
      message: {
        filter: {
          protocol: "http://simple-messaging-protocol3.xyz",
        },
      },
    });

    console.log(records); 

```

results in no results and: 

web5.ts:149 Sync failed due to error:  Error: TODO: message not found
    at bve.<anonymous> (sync-api.ts:348:13)
    at Generator.next (<anonymous>)
    at a (sync-api.ts:17:23)

**Comment by michaelneale** [comment]
here is some test code - run it at 2 seperate URLs so they get their own dids: https://gist.github.com/michaelneale/2e1e1a50444c5272784b29b7d457a414
